name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    container: ${{ format('swift:{0}-{1}', matrix.swift.version, matrix.os) }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        os:
          - noble
        swift:
          - version: "6.2"
    steps:
    - uses: actions/checkout@v4
    - uses: brightdigit/swift-build@v1.2.1

  build-macos:
    name: Build on macOS
    runs-on: ${{ matrix.runs-on }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        include:
          # SPM Build Matrix
          - runs-on: macos-26
            xcode: "/Applications/Xcode_26.0.app"
          - runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
    steps:
    - uses: actions/checkout@v4
    - uses: brightdigit/swift-build@v1.2.1
      with:
        xcode: ${{ matrix.xcode }}
